name: movie_match_splash_screen
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  image_picker: ^0.7.4
  image_cropper: ^1.4.0
  select_profile_photo: ^0.1.6
  date_time_picker_tr: ^0.1.4
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

 
  assets:
     - assets/images/